### PR TITLE
Update sales-account-manager.md vacancy

### PR DESCRIPTION
**Pull request by nstymnv**
Changed the name of a vacancy and the first abstract with a short description.

### CODE REVIEW

**Review by nstymnv — COMMENTED** [review]
I mean, changed the duties, not the requirements, confused different commits:)

**Comment by atatarenko** [comment]
@nstymnv I was not added as a reviewer but I made a quick glance and it looks like we're dealing with another sort of vacancy with different expectations about experience and skills. What do you think about an idea to create another file but leave the original one as-is?

**Comment by nstymnv** [comment]
@atatarenko, yeah, I was thinking if I should create another file or edit this one, but decided this way. No problem, I'll create a new one. Would you like me to add you as a reviewer as well?

**Comment by atatarenko** [comment]
@nstymnv yeah, I think it's be useful because I can help with Github stuff, just in case.

**Comment by nstymnv** [comment]
@atatarenko, done! 
@yuliagaranok , @atatarenko, guys, I've made another file with a vacancy, so I'll close this pull request not no confuse them.

**Pull request closed without merging**
